### PR TITLE
WIP Initial TV support for iOS 12.2

### PR DESCRIPTION
**Pull request by Ben305**
Initial TV support for iOS 12.2

### CODE REVIEW

**Comment by Ben305** [comment]
@merdok Please do not merge yet, this is still unfinished. Just wanted to share my progress.

**Comment by merdok** [comment]
Thanks! Installing the beta right now. Will work on this during the weekend.

**Comment by merdok** [comment]
@Ben305 does this code work for you:

```
    this.volumeService
        .getCharacteristic(Characteristic.Mute)
        .on('get', this.getMuteState.bind(this))
        .on('set', this.setMuteState.bind(this));
```

Will the TV get muted when you mute your iPhone with the mute switch? I am using my iPad which does not have a mute switch so i cannot test it...

**Comment by merdok** [comment]
Included in the latest release.

**Pull request closed without merging**
