### PR TITLE
Update LgTvController.js

### PR DESCRIPTION
**Pull request by VladLikov**

### CODE REVIEW

**Comment by merdok** [comment]
Hello,
why do you provide this pull request? Did the "brightness" changed to "oled_light" on your tv?

**Comment by VladLikov** [comment]
Hello,

I have an LG CX TV, it's an Oled TV and "brightness" settings from your code doesn't work properly.

**Comment by merdok** [comment]
Yeah, but how about other TVs (especially non OLED TVs) which does not have "oled_light"?
Does  "brightness" throw an error on your TV?  Cannot we leave "brightness" in and add "oled_light" additionally?

**Comment by VladLikov** [comment]
Yes, of course we need to leave "brightness" in. And will be great if you add "oled_light" additionally. Thank you.

**Comment by merdok** [comment]
Can you make the necessary change, please? We could then merge your pull request.

**Comment by VladLikov** [comment]
Unfortunately I don't have much experience in JS. If you can do it by yourself it will be great.

**Comment by merdok** [comment]
From where do you have the `oled_light` settings key? Unfortunately it does not exists...

**Pull request closed without merging**
