### PR TITLE
Added triggers to allow repsonding on pressing volume up/down on the …

### PR DESCRIPTION
**Pull request by rooi**
Hi,

Added a stateless switch with two buttons to allow using remote control volume up/down action in homekit automation. It's possible to add the channel up/down on the same switch.

Someone asked for something similar in issue #120. I'm using it to control my receiver with the tv volume which does not respond to CEC actions.

### CODE REVIEW

**Comment by merdok** [comment]
Do i understand correctly that his creates 2 new accessories which only basically can be used as triggers for actions?

**Comment by rooi** [comment]
One accessory is created since these can hold multiple buttons (I've seen a maximum of four). When adding channel or other triggers, it would still be one accessory. I thought about adding a config for it, but didn't think it would be necessary since it's only one accessory. Your choice obviously, if you'd decide to merge

**Comment by merdok** [comment]
But you create 2 stateless switches so i guess of them will appear in HomeKit then? It would be much cleaner if this could be integrated in the existing volume accessories...

**Comment by rooi** [comment]
In apple's home app they are grouped under a single icon (similar to a hue dimmer switch which has one icon for a switch with four buttons inside https://9to5mac.com/2017/10/03/philips-hue-homekit-tap-dimmer-switch-motion-sensor/)
I agree that it would be cleaner to add the functionality under de existing volume accessories, but it could cause racing conditions. 
If I'm correct, it is not trivial to determine if a volume up request that triggers ssap://audio/getStatus originates from a physical remote or the homekit switches. Perhaps it's possible to use the on/off state to 'register' the origin. 
For example, removing the setTimeOut from setVolumeSwitch and turn the switch to off when the audio status changes. If a up/down switch is on, that would mean it originated from the homekit buttons. In other cases, the changes originates from the physical remote of the slider.

What do you think? Should I give this a try instead to the stateless switches?

**Comment by merdok** [comment]
How about triggering an action when the volume reaches a certain level? I guess this is still missing. 
We have two cases here where the user can select either the volume up/down stateless switches and or the volume slider, both of them should work. 
I guess integrating this into the existing volume accessories is a little bit complicated(confusing) since i basically use stateless switches for that which really should not have a state (even if they are just emulated in this case). 
I guess this is something which needs to be considered good how to solve this.

**Comment by rooi** [comment]
That would mean many actions to let it respond properly. Right now it responds to all tv volume up/down presses and my receiver is virtually linked.
It's unfortunate that we can't use the stateless switches from homekit apps.

**Comment by merdok** [comment]
True... Maybe someday we will be able to do that. 
For now let me think about it and test the code on my TV.

**Comment by merdok** [comment]
Added in the latest release using the existing volumeup and volumedown buttons.

**Pull request closed without merging**
